# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    default_language_version:
      python: python3.10.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
        types: [python]

-   repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
    -   id: black
        language_version: python3.10
        line-length: 99

-   repo: https://github.com/pycqa/pylint
    rev: v2.11.1
    hooks:
    -   id: pylint
        args:
        - --max-line-length=99
        - --ignore-imports=yes
        - -d C0303,W1401,C0111,C0116,E0401
        - --fail-under=8

-   repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
        name: isort (python)
