from pathlib import Path


class Settings:
    """App settings"""

    HOST: str = "127.0.0.1"
    PORT: int = 5560
    BASE_DIR = Path(__file__).resolve().parent.parent.parent

    # These directories are generated by the generate_certificates script
    KEYS_DIR = BASE_DIR / "certificates"
    PUBLIC_KEYS_DIR = KEYS_DIR / "public_keys"
    SECRET_KEYS_DIR = KEYS_DIR / "private_keys"

    MATH_ALLOWED_NAMES = {
        k: v for k, v in __import__("math").__dict__.items() if not k.startswith("__")
    }

    OS_ALLOWED_COMMANDS = ("cp", "ls", "cat", "sleep")


settings = Settings()
