from pathlib import Path


class Settings:
    """App settings"""

    HOST: str = "127.0.0.1"
    PORT: int = 5560
    BASE_DIR = Path(__file__).resolve().parent.parent.parent

    # These directories are generated by the generate_certificates script
    KEYS_DIR = BASE_DIR / "certificates"
    PUBLIC_KEYS_DIR = KEYS_DIR / "public_keys"
    SECRET_KEYS_DIR = KEYS_DIR / "private_keys"


settings = Settings()
